### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by sinchb** [no13bus/redispapa#2]
Got an KeyError
Ubuntu 14.04

```
linuxdev3@linuxdev3:~/open/redispapa$ fg
python run.py

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/socketio/virtsocket.py", line 403, in _receiver_loop
    retval = pkt_ns.process_packet(pkt)
  File "/usr/local/lib/python2.7/dist-packages/socketio/namespace.py", line 155, in process_packet
    return self.process_event(packet)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 60, in process_event
    return self.socketio._dispatch_message(app, self, message, args)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 135, in _dispatch_message
    ret = self.messages[namespace.ns_name][message](*args)
  File "run.py", line 165, in client_command
    args = message['args']
KeyError: 'args'
<Greenlet at 0x7f13fe143b90: <bound method Socket._receiver_loop of <socketio.virtsocket.Socket object at 0x7f13fded34d0>>> failed with KeyError
```

**Comment by no13bus** [comment]
what does `fg` mean??
Do you type `sudo pip install -r requirement.txt` before you run `python run.py`? Because flask-socketio just support socket.io whose version is below 0.9.16.
